version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build: .
    container_name: webServer
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/studyBuddy

volumes:
  mongo-data:
